Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using ozzy_mvc.Data;
using ozzy_mvc.Models;

namespace ozzy_mvc.Controllers
{
    public class AuthController : Controller
    {
        private readonly OzzyMvcContext _context;

        public AuthController(OzzyMvcContext context)
        {
            _context = context;
        }

        // GET: Auth/Login
        public IActionResult Login(string Username)
        {   
            ViewData["Username"] = Username;
            return View();
        }

        // POST: Auth/Login
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([Bind("Username")] string Username, [Bind("Password")] string Password)
        {

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Username == Username);
            if (student == null)
            {
                return NotFound();
            }

            if (student.IsBlacklisted) {
                return View();
            }

            if (student.Password != Password) {
                return View();
            }

            CookieOptions cookieOptions = new CookieOptions();            
            HttpContext.Response.Cookies.Append("CurrentID", student.StudentID.ToString(), cookieOptions);
            HttpContext.Response.Cookies.Append("CurrentUsername", student.Username, cookieOptions);

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Logout()
        {

            CookieOptions cookieOptions = new CookieOptions();            
            HttpContext.Response.Cookies.Delete("CurrentID", cookieOptions);
            HttpContext.Response.Cookies.Delete("CurrentUsername", cookieOptions);

            return RedirectToAction("Index", "Home");
        }

    }
}

Controllers/LabController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ozzy_mvc.Models;
using ozzy_mvc.Data;

namespace ozzy_mvc.Controllers
{

    public class LabController : Controller
    {

        private readonly OzzyMvcContext _context;

        public LabController(OzzyMvcContext context)
        {
            _context = context;
        }

        public IActionResult ESL()
        {

            var query = from equipment in _context.Set<Equipment>()
                        join booking in _context.Set<Booking>()
                            on equipment.EquipmentID equals booking.EquipmentID
                        select new { equipment, booking };

            EquipmentType[] items = {EquipmentType.OSCILLOSCOPE,
                                    EquipmentType.SIGNAL_GENERATOR,
                                    EquipmentType.MULTIMETER,
                                    EquipmentType.POWER_SUPPLY,
                                    EquipmentType.LOGIC_TRAINER};


            int[] days = { 1, 2, 3, 4, 5, 6 };

            TimeSlot[] slots = {TimeSlot.MORNING,
                                TimeSlot.AFTERNOON,
                                TimeSlot.EVENING};

            var now = DateTime.Now;
            var current_date = now.Date;

            int[,,] results = new int[items.Count(),6,3];

            var i = 0;
            var j = 0;
            var k = 0;

            foreach (EquipmentType item in items)
            {

                var equipmentTemp = _context.Equipment.Where(i => i.EquipmentType == item);

                List<Equipment> eq = equipmentTemp.ToList<Equipment>();

                var fullAmount = eq.Count();

                j=0;
                foreach (int day in days)
                {
                    current_date = current_date.AddDays(1);
                    k=0;
                    foreach (TimeSlot slot in slots)
                    {

                        var data = query.Select(x =>
                            new EquipmentInventory
                            {
                                EquipmentID = x.equipment.EquipmentID,
                                EquipmentName = x.equipment.EquipmentName,
                                EquipmentType = x.equipment.EquipmentType,
                                Description = x.equipment.Description,
                                LabName = x.equipment.LabName,
                                TimeSlot = x.booking.TimeSlot,
                                Date = x.booking.Date,
                                DateStr = String.Format("{0:M/d/yyyy}", x.booking.Date),
                                StudentID = x.booking.StudentID
                            }
                        ).Where(i => i.EquipmentType == item && i.Date == current_date && i.TimeSlot == slot);

                        List<EquipmentInventory> inventory = data.ToList<EquipmentInventory>();

                        results[i,j,k] = fullAmount - inventory.Count();
                        k++;
                    }
                    j++;
                }
                i++;
            }
            
            ViewData["results"] = results;
            
            return View();
        }

        public IActionResult HCRL()
        {
            var query = from equipment in _context.Set<Equipment>()
                        join booking in _context.Set<Booking>()
                            on equipment.EquipmentID equals booking.EquipmentID
                        select new { equipment, booking };

            EquipmentType[] items = {EquipmentType.MONITOR,
                                    EquipmentType.PROJECTOR};


            int[] days = { 1, 2, 3, 4, 5, 6 };

            TimeSlot[] slots = {TimeSlot.MORNING,
                                TimeSlot.AFTERNOON,
                                TimeSlot.EVENING};

            var now = DateTime.Now;
            var current_date = now.Date;

            int[,,] results = new int[items.Count(),6,3];

            var i = 0;
            var j = 0;
            var k = 0;

            foreach (EquipmentType item in items)
            {

                var equipmentTemp = _context.Equipment.Where(i => i.EquipmentType == item);

                List<Equipment> eq = equipmentTemp.ToList<Equipment>();

                var fullAmount = eq.Count();

                j=0;
                foreach (int day in days)
                {
                    current_date = current_date.AddDays(1);
                    k=0;
                    foreach (TimeSlot slot in slots)
                    {

                        var data = query.Select(x =>
                            new EquipmentInventory
                            {
                                EquipmentID = x.equipment.EquipmentID,
                                EquipmentName = x.equipment.EquipmentName,
                                EquipmentType = x.equipment.EquipmentType,
                                Description = x.equipment.Description,
                                LabName = x.equipment.LabName,
                                TimeSlot = x.booking.TimeSlot,
                                Date = x.booking.Date,
                                DateStr = String.Format("{0:M/d/yyyy}", x.booking.Date),
                                StudentID = x.booking.StudentID
                            }
                        ).Where(i => i.EquipmentType == item && i.Date == current_date && i.TimeSlot == slot);

                        List<EquipmentInventory> inventory = data.ToList<EquipmentInventory>();

                        results[i,j,k] = fullAmount - inventory.Count();
                        k++;
                    }
                    j++;
                }
                i++;
            }
            
            ViewData["results"] = results;
            
            return View();
        }
        public IActionResult Hardware()
        {
            var query = from equipment in _context.Set<Equipment>()
                        join booking in _context.Set<Booking>()
                            on equipment.EquipmentID equals booking.EquipmentID
                        select new { equipment, booking };

            EquipmentType[] items = {EquipmentType.ELECTRIC_DRILL_SET,
                                    EquipmentType.SCREWDRIVER_SET,
                                    EquipmentType.SOLDERING_IRON,
                                    EquipmentType.HAMMER,
                                    EquipmentType.HACKSAW,
                                    EquipmentType.PLIERS,
                                    EquipmentType.CROWBAR,
                                    EquipmentType.WRENCH};

            int[] days = { 1, 2, 3, 4, 5, 6 };

            TimeSlot[] slots = {TimeSlot.MORNING,
                                TimeSlot.AFTERNOON,
                                TimeSlot.EVENING};

            var now = DateTime.Now;
            var current_date = now.Date;

            int[,,] results = new int[items.Count(),6,3];

            var i = 0;
            var j = 0;
            var k = 0;

            foreach (EquipmentType item in items)
            {

                var equipmentTemp = _context.Equipment.Where(i => i.EquipmentType == item);

                List<Equipment> eq = equipmentTemp.ToList<Equipment>();

                var fullAmount = eq.Count();

                j=0;
                foreach (int day in days)
                {
                    current_date = current_date.AddDays(1);
                    k=0;
                    foreach (TimeSlot slot in slots)
                    {

                        var data = query.Select(x =>
                            new EquipmentInventory
                            {
                                EquipmentID = x.equipment.EquipmentID,
                                EquipmentName = x.equipment.EquipmentName,
                                EquipmentType = x.equipment.EquipmentType,
                                Description = x.equipment.Description,
                                LabName = x.equipment.LabName,
                                TimeSlot = x.booking.TimeSlot,
                                Date = x.booking.Date,
                                DateStr = String.Format("{0:M/d/yyyy}", x.booking.Date),
                                StudentID = x.booking.StudentID
                            }
                        ).Where(i => i.EquipmentType == item && i.Date == current_date && i.TimeSlot == slot);

                        List<EquipmentInventory> inventory = data.ToList<EquipmentInventory>();

                        results[i,j,k] = fullAmount - inventory.Count();
                        k++;
                    }
                    j++;
                }
                i++;
            }
            
            ViewData["results"] = results;
            return View();
        }

        public IActionResult Network()
        {
            var query = from equipment in _context.Set<Equipment>()
                        join booking in _context.Set<Booking>()
                            on equipment.EquipmentID equals booking.EquipmentID
                        select new { equipment, booking };

            EquipmentType[] items = {EquipmentType.LAN_CAT6_CABLE,
                                    EquipmentType.RJ45_CRIMPING_TOOL,
                                    EquipmentType.ROUTER,
                                    EquipmentType.SWITCH};

            int[] days = { 1, 2, 3, 4, 5, 6 };

            TimeSlot[] slots = {TimeSlot.MORNING,
                                TimeSlot.AFTERNOON,
                                TimeSlot.EVENING};

            var now = DateTime.Now;
            var current_date = now.Date;

            int[,,] results = new int[items.Count(),6,3];

            var i = 0;

Views/Shared/_AdminNavbar.cshtml
<nav>
    <ul>
        <li>
            <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="dropdown" id="dropdown" general="">
            <div class="dropbtn">LAB</div>
            <div class="dropdown-content">
                <a asp-area="" asp-controller="Lab" asp-action="Hardware">Hardware</a>
                <a asp-area="" asp-controller="Lab" asp-action="HCRL">HCRL</a>
                <a asp-area="" asp-controller="Lab" asp-action="Robot">Robot & IoT</a>
                <a asp-area="" asp-controller="Lab" asp-action="ESL">ESL</a>
                <a asp-area="" asp-controller="Lab" asp-action="Network">Network</a>
            </div>
        </li>
            <a asp-area="" asp-controller="Home" asp-action="Admin"><li class="dropdown" id="dropdown" general="">
                <div class="dropbtn">Admin Panel</div>
                <div class="dropdown-content">
                    Admin Tools
                    <a asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                    <a asp-area="" asp-controller="Booking" asp-action="Index">Booking</a>
                    <a asp-area="" asp-controller="Equipment" asp-action="Index">Equipment</a>
                </div>
            </a>
        </li>
        <li class="dropdown" style="float: right;">
            <button class="user-button" onclick="myFunction()">
                <div class="profile-picture">
                    @Context.Request.Cookies["CurrentUsername"].Substring(0,1)
                </div>
                &emsp; @Context.Request.Cookies["CurrentUsername"] &emsp;
            </button>
            <div class="dropdown-content" id="myDropdown" notgeneral="">
                <a asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
            </div>         
        </li>
    </ul>
</nav>

<script>
function myFunction() { 
    document.getElementById("myDropdown").classList.toggle("dropdown-content-user-button"); //TOGGLE BUTTON
    document.querySelector('nav').style.setProperty('--enable', '#88490e');   //CHANGE COLOR TO #88490e WHEN ACTIVE
}
    
window.onclick = function(e) {
    if (!e.target.matches('.user-button')) {
        if (document.getElementById("myDropdown").classList.contains('dropdown-content-user-button')) {
            document.getElementById("myDropdown").classList.remove('dropdown-content-user-button');
        }   //Close the dropdown if the user clicks outside of it
    }
    if (!document.getElementById("myDropdown").classList.contains('dropdown-content-user-button')) {
        document.querySelector('nav').style.setProperty('--enable', '#684933');   
    }   //CHANGE COLOR BACK (#684933) WHEN NOT ACTIVE
}
</script>

@* <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ozzy_mvc</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Admin">Home</a>
                </li>
                <li>
                    <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Index">Booking</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Equipment"
                        asp-action="Index">Equipment</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
</header> *@

Views/Shared/_Footer.cshtml
<footer>
    <h2>CONTACT US</h2>
    
    <p>ตึก ECC เลขที่ 1 ซอยฉลองกรุง 1 เขตลาดกระบัง แขวงลาดกระบัง กรุงเทพฯ 10520<br>โทรศัพท์ : 02-329-8341 ~ 2, โทรสาร : 02-329-8343, อีเมล : cekmitl@kmitl.ac.th</p>
    @* <p>Phone : 02-329-8341 E-mail : cekmitl@kmitl.ac.th</p> *@
</footer>

Views/Shared/_GuestNavbar.cshtml
<nav>
    <ul>
        <li>
            <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="dropdown" id="dropdown" general="">
            <div class="dropbtn">LAB</div>
            <div class="dropdown-content">
                <a asp-area="" asp-controller="Lab" asp-action="Hardware">Hardware</a>
                <a asp-area="" asp-controller="Lab" asp-action="HCRL">HCRL</a>
                <a asp-area="" asp-controller="Lab" asp-action="Robot">Robot & IoT</a>
                <a asp-area="" asp-controller="Lab" asp-action="ESL">ESL</a>
                <a asp-area="" asp-controller="Lab" asp-action="Network">Network</a>
            </div>
        </li>
        <li style="float:right">
            <a class="user-button" asp-area="" asp-controller="Auth" asp-action="Login">&emsp; Login &emsp;</a>
        </li>
    </ul>
</nav>

@* <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ozzy_mvc</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Create">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                </li>
            </ul>
        </div>
    </nav>
</header> *@

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - ozzy_mvc</title>
        <link rel="stylesheet" href="~/css/site.css" />
    </head>

    <body>
        @if (Context.Request.Cookies["CurrentUsername"] == "admin")
        {
            @Html.Partial("_AdminNavbar")
        }
        else if (Context.Request.Cookies["CurrentUsername"] != null)
        {
            @Html.Partial("_StudentNavbar")
        }
        else
        {
            @Html.Partial("_GuestNavbar")
        }

        @if (Context.Request.Path=="/Lab/Hardware"  || Context.Request.Path=="/Lab/HCRL" || 
             Context.Request.Path=="/Lab/Robot"     || Context.Request.Path=="/Lab/ESL" ||
             Context.Request.Path=="/Lab/Network"   || Context.Request.Path=="/"){   
            <main role="main" class="withfooter">
                    @RenderBody()
            </main> 
        }
        else{
            <main role="main" class="fitscreen">
                    @RenderBody()
            </main> 
        }

        @if (Context.Request.Path=="/Lab/Hardware"  || Context.Request.Path=="/Lab/HCRL" || 
             Context.Request.Path=="/Lab/Robot"     || Context.Request.Path=="/Lab/ESL" ||
             Context.Request.Path=="/Lab/Network"   || Context.Request.Path=="/"){
            @Html.Partial("_Footer")
        }
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>

</html>

Views/Shared/_StudentNavbar.cshtml
<nav>
    <ul>
        <li>
            <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="dropdown" id="dropdown" general="">
            <div class="dropbtn">LAB</div>
            <div class="dropdown-content">
                <a asp-area="" asp-controller="Lab" asp-action="Hardware">Hardware</a>
                <a asp-area="" asp-controller="Lab" asp-action="HCRL">HCRL</a>
                <a asp-area="" asp-controller="Lab" asp-action="Robot">Robot & IoT</a>
                <a asp-area="" asp-controller="Lab" asp-action="ESL">ESL</a>
                <a asp-area="" asp-controller="Lab" asp-action="Network">Network</a>
            </div>
        </li>
        <li class="dropdown" style="float: right;">
            <button class="user-button" onclick="myFunction()">
                <div class="profile-picture">
                    @Context.Request.Cookies["CurrentUsername"].Substring(0,1)
                </div>
                &emsp;@Context.Request.Cookies["CurrentUsername"] &emsp;
            </button>
            <div class="dropdown-content" id="myDropdown" notgeneral="">
                <a asp-area="" asp-controller="Student" asp-action="Edit" asp-route-id=@Context.Request.Cookies["CurrentID"]>My Profile</a>
                <a asp-area="" asp-controller="Equipment" asp-action="Inventory" asp-route-id=@Context.Request.Cookies["CurrentID"]>Inventory</a>
                <a asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
            </div>         
        </li>    
    </ul>
</nav>


<script>
function myFunction() { 
    document.getElementById("myDropdown").classList.toggle("dropdown-content-user-button"); //TOGGLE BUTTON
    document.querySelector('nav').style.setProperty('--enable', '#88490e');   //CHANGE COLOR TO #88490e WHEN ACTIVE
}
    
window.onclick = function(e) {
    if (!e.target.matches('.user-button')) {
        if (document.getElementById("myDropdown").classList.contains('dropdown-content-user-button')) {
            document.getElementById("myDropdown").classList.remove('dropdown-content-user-button');
        }   //Close the dropdown if the user clicks outside of it
    }
    if (!document.getElementById("myDropdown").classList.contains('dropdown-content-user-button')) {
        document.querySelector('nav').style.setProperty('--enable', '#684933');   
    }   //CHANGE COLOR BACK (#684933) WHEN NOT ACTIVE
}
</script>

@* <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ozzy_mvc</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">My
                        Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
</header> *@