Controllers/EquipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ozzy_mvc.Data;
using ozzy_mvc.Models;

namespace ozzy_mvc.Controllers
{
    public class EquipmentController : Controller
    {
        private readonly OzzyMvcContext _context;

        public EquipmentController(OzzyMvcContext context)
        {
            _context = context;
        }

        // GET: Equipment
        public async Task<IActionResult> Index()
        {
            return View(await _context.Equipment.ToListAsync());
        }

        public async Task<IActionResult> Inventory(Guid id)
        {

            var query = from equipment in _context.Set<Equipment>()
            join booking in _context.Set<Booking>()
                on equipment.EquipmentID equals booking.EquipmentID
            select new { equipment,booking };

            var data = query.Select(x =>
                new EquipmentInventory { EquipmentID = x.equipment.EquipmentID,
                    EquipmentName = x.equipment.EquipmentName,
                    EquipmentType = x.equipment.EquipmentType,
                    Description = x.equipment.Description,
                    LabName = x.equipment.LabName,
                    TimeSlot = x.booking.TimeSlot,
                    Date = x.booking.Date,
                    DateStr = String.Format("{0:M/d/yyyy}", x.booking.Date),
                    StudentID = x.booking.StudentID
                }
            ).Where(i => i.StudentID == id).OrderBy(i => i.EquipmentName).ThenBy(i => i.Date);
            
            List<EquipmentInventory> eq = data.ToList<EquipmentInventory>(); 

            return View(eq);
        }

        // GET: Equipment/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = await _context.Equipment
                .FirstOrDefaultAsync(m => m.EquipmentID == id);
            if (equipment == null)
            {
                return NotFound();
            }

            return View(equipment);
        }

        // GET: Equipment/Create
        public IActionResult Create()
        {
            ViewData["EquipmentType"] = new SelectList(Enum.GetValues(typeof(EquipmentType)));
            ViewData["LabName"] = new SelectList(Enum.GetValues(typeof(Lab)));
            return View();
        }

        // POST: Equipment/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EquipmentID, EquipmentType, EquipmentName,Description,LabName")] Equipment equipment)
        {
            if (ModelState.IsValid)
            {
                equipment.EquipmentID = Guid.NewGuid();
                _context.Add(equipment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(equipment);
        }

        // GET: Equipment/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ViewData["EquipmentType"] = new SelectList(Enum.GetValues(typeof(EquipmentType)));
            ViewData["LabName"] = new SelectList(Enum.GetValues(typeof(Lab)));

            var equipment = await _context.Equipment.FindAsync(id);
            if (equipment == null)
            {
                return NotFound();
            }
            return View(equipment);
        }

        // POST: Equipment/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("EquipmentID,EquipmentType,EquipmentName,Description,LabName")] Equipment equipment)
        {
            if (id != equipment.EquipmentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(equipment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EquipmentExists(equipment.EquipmentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(equipment);
        }

        // GET: Equipment/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = await _context.Equipment
                .FirstOrDefaultAsync(m => m.EquipmentID == id);
            if (equipment == null)
            {
                return NotFound();
            }

            return View(equipment);
        }

        // POST: Equipment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var equipment = await _context.Equipment.FindAsync(id);
            _context.Equipment.Remove(equipment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EquipmentExists(Guid id)
        {
            return _context.Equipment.Any(e => e.EquipmentID == id);
        }
    }

    public class EquipmentInventory
    {
        public Guid EquipmentID { get; set; }
        public String EquipmentName { get; set; }
        public EquipmentType EquipmentType { get; set; }
        public String Description { get; set; }
        public Lab LabName  { get; set; }
        public TimeSlot TimeSlot { get; set; }
        public DateTime Date { get; set; }
        public String DateStr { get; set; }
        public Guid StudentID {get; set; }
        public Guid BookingID {get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ozzy_mvc.Models;

namespace ozzy_mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Admin()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LabController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ozzy_mvc.Models;
using ozzy_mvc.Data;

namespace ozzy_mvc.Controllers
{

    public class LabController : Controller
    {

        private readonly OzzyMvcContext _context;

        public LabController(OzzyMvcContext context)
        {
            _context = context;
        }

        public IActionResult ESL()
        {

            var query = from equipment in _context.Set<Equipment>()
                        join booking in _context.Set<Booking>()
                            on equipment.EquipmentID equals booking.EquipmentID
                        select new { equipment, booking };

            EquipmentType[] items = {EquipmentType.OSCILLOSCOPE,
                                    EquipmentType.SIGNAL_GENERATOR,
                                    EquipmentType.MULTIMETER,
                                    EquipmentType.POWER_SUPPLY,
                                    EquipmentType.LOGIC_TRAINER};


            int[] days = { 1, 2, 3, 4, 5, 6 };

            TimeSlot[] slots = {TimeSlot.MORNING,
                                TimeSlot.AFTERNOON,
                                TimeSlot.EVENING};

            var now = DateTime.Now;
            var current_date = now.Date;

            int[,,] results = new int[items.Count(),6,3];

            var i = 0;
            var j = 0;
            var k = 0;

            foreach (EquipmentType item in items)
            {

                var equipmentTemp = _context.Equipment.Where(i => i.EquipmentType == item);

                List<Equipment> eq = equipmentTemp.ToList<Equipment>();

                var fullAmount = eq.Count();

                j=0;
                foreach (int day in days)
                {
                    current_date = current_date.AddDays(1);
                    k=0;
                    foreach (TimeSlot slot in slots)
                    {

                        var data = query.Select(x =>
                            new EquipmentInventory
                            {
                                EquipmentID = x.equipment.EquipmentID,
                                EquipmentName = x.equipment.EquipmentName,
                                EquipmentType = x.equipment.EquipmentType,
                                Description = x.equipment.Description,
                                LabName = x.equipment.LabName,
                                TimeSlot = x.booking.TimeSlot,
                                Date = x.booking.Date,
                                DateStr = String.Format("{0:M/d/yyyy}", x.booking.Date),
                                StudentID = x.booking.StudentID
                            }
                        ).Where(i => i.EquipmentType == item && i.Date == current_date && i.TimeSlot == slot);

                        List<EquipmentInventory> inventory = data.ToList<EquipmentInventory>();

                        results[i,j,k] = fullAmount - inventory.Count();
                        k++;
                    }
                    j++;
                }
                i++;
            }
            
            ViewData["results"] = results;
            
            return View();
        }

        public IActionResult HCRL()
        {
            var query = from equipment in _context.Set<Equipment>()
                        join booking in _context.Set<Booking>()
                            on equipment.EquipmentID equals booking.EquipmentID
                        select new { equipment, booking };

            EquipmentType[] items = {EquipmentType.MONITOR,
                                    EquipmentType.PROJECTOR};


            int[] days = { 1, 2, 3, 4, 5, 6 };

            TimeSlot[] slots = {TimeSlot.MORNING,
                                TimeSlot.AFTERNOON,
                                TimeSlot.EVENING};

            var now = DateTime.Now;
            var current_date = now.Date;

            int[,,] results = new int[items.Count(),6,3];

            var i = 0;
            var j = 0;
            var k = 0;

            foreach (EquipmentType item in items)
            {

                var equipmentTemp = _context.Equipment.Where(i => i.EquipmentType == item);

                List<Equipment> eq = equipmentTemp.ToList<Equipment>();

                var fullAmount = eq.Count();

                j=0;
                foreach (int day in days)
                {
                    current_date = current_date.AddDays(1);
                    k=0;
                    foreach (TimeSlot slot in slots)
                    {

                        var data = query.Select(x =>
                            new EquipmentInventory
                            {
                                EquipmentID = x.equipment.EquipmentID,
                                EquipmentName = x.equipment.EquipmentName,
                                EquipmentType = x.equipment.EquipmentType,
                                Description = x.equipment.Description,
                                LabName = x.equipment.LabName,
                                TimeSlot = x.booking.TimeSlot,
                                Date = x.booking.Date,
                                DateStr = String.Format("{0:M/d/yyyy}", x.booking.Date),
                                StudentID = x.booking.StudentID
                            }
                        ).Where(i => i.EquipmentType == item && i.Date == current_date && i.TimeSlot == slot);

                        List<EquipmentInventory> inventory = data.ToList<EquipmentInventory>();

                        results[i,j,k] = fullAmount - inventory.Count();
                        k++;
                    }
                    j++;
                }
                i++;
            }
            
            ViewData["results"] = results;
            
            return View();
        }
        public IActionResult Hardware()
        {
            var query = from equipment in _context.Set<Equipment>()
                        join booking in _context.Set<Booking>()
                            on equipment.EquipmentID equals booking.EquipmentID
                        select new { equipment, booking };

            EquipmentType[] items = {EquipmentType.ELECTRIC_DRILL_SET,
                                    EquipmentType.SCREWDRIVER_SET,
                                    EquipmentType.SOLDERING_IRON,
                                    EquipmentType.HAMMER,
                                    EquipmentType.HACKSAW,
                                    EquipmentType.PLIERS,
                                    EquipmentType.CROWBAR,
                                    EquipmentType.WRENCH};

            int[] days = { 1, 2, 3, 4, 5, 6 };

            TimeSlot[] slots = {TimeSlot.MORNING,
                                TimeSlot.AFTERNOON,
                                TimeSlot.EVENING};

            var now = DateTime.Now;
            var current_date = now.Date;

            int[,,] results = new int[items.Count(),6,3];

            var i = 0;
            var j = 0;
            var k = 0;

            foreach (EquipmentType item in items)
            {

                var equipmentTemp = _context.Equipment.Where(i => i.EquipmentType == item);

                List<Equipment> eq = equipmentTemp.ToList<Equipment>();

                var fullAmount = eq.Count();

                j=0;
                foreach (int day in days)
                {
                    current_date = current_date.AddDays(1);
                    k=0;
                    foreach (TimeSlot slot in slots)
                    {

                        var data = query.Select(x =>
                            new EquipmentInventory
                            {
                                EquipmentID = x.equipment.EquipmentID,
                                EquipmentName = x.equipment.EquipmentName,
                                EquipmentType = x.equipment.EquipmentType,
                                Description = x.equipment.Description,
                                LabName = x.equipment.LabName,
                                TimeSlot = x.booking.TimeSlot,
                                Date = x.booking.Date,
                                DateStr = String.Format("{0:M/d/yyyy}", x.booking.Date),
                                StudentID = x.booking.StudentID
                            }
                        ).Where(i => i.EquipmentType == item && i.Date == current_date && i.TimeSlot == slot);

                        List<EquipmentInventory> inventory = data.ToList<EquipmentInventory>();

                        results[i,j,k] = fullAmount - inventory.Count();
                        k++;
                    }
                    j++;
                }
                i++;
            }
            
            ViewData["results"] = results;
            return View();
        }

        public IActionResult Network()
        {
            var query = from equipment in _context.Set<Equipment>()
                        join booking in _context.Set<Booking>()
                            on equipment.EquipmentID equals booking.EquipmentID
                        select new { equipment, booking };

            EquipmentType[] items = {EquipmentType.LAN_CAT6_CABLE,
                                    EquipmentType.RJ45_CRIMPING_TOOL,
                                    EquipmentType.ROUTER,
                                    EquipmentType.SWITCH};

            int[] days = { 1, 2, 3, 4, 5, 6 };

            TimeSlot[] slots = {TimeSlot.MORNING,
                                TimeSlot.AFTERNOON,
                                TimeSlot.EVENING};

            var now = DateTime.Now;
            var current_date = now.Date;

            int[,,] results = new int[items.Count(),6,3];

            var i = 0;

Views/Home/Admin.cshtml
@{
    ViewData["Title"] = "Admin Panel";
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="content-type" content="text/html" charset="utf-8" />
    <link rel="StyleSheet" href="~/css/admin.css" />

</head>

<body>
    <div class="banner">
        Welcome Admin
    </div>
    <div class="contain-btn">
        <a asp-controller="Student" asp-action="Index" class="btn">
            <p>Student Management</p>
        </a>
        <a asp-controller="Booking" asp-action="Index" class="btn">
            <p>Booking Management</p>
        </a>
        <a asp-controller="Equipment" asp-action="Index" class="btn">
            <p>Equipment Management</p>
        </a>
    </div>
</body>

</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "KMITL Loboratory System";
}
<!--
<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    <h1>This is my world
    </h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="content-type" content="text/html" charset="utf-8" />
    <link rel="StyleSheet" href="~/css/home.css" />

</head>

<body>
    <div class="banner">
        KMITL Laboratory System
    </div>
    <div class='content-container'>
        <div class='carousel'>
            <input checked='checked' class='carousel__activator' id='carousel-slide-activator-1' name='carousel' type='radio'>
            <input class='carousel__activator' id='carousel-slide-activator-2' name='carousel' type='radio'>
            <div class='carousel__controls'>
                <label class='carousel__control carousel__control--forward' for='carousel-slide-activator-2'>
              <!--👉-->>
            </label>
            </div>
            <div class='carousel__controls'>
                <label class='carousel__control carousel__control--backward' for='carousel-slide-activator-1'>
              <!--👈--><
            </label>
            </div>
                
            <div class='carousel__screen'>
                <div class='carousel__track'>
                    <a asp-area="" asp-controller="Lab" asp-action="Hardware">
                        <div class='carousel__item carousel__item--desktop-in-3'>
                            <div class='demo-content'>              
                                <img src="~/image/LAB/HARDWARE/1 - HARDWARE.jpg" alt="Hardware Lab">
                                <div class='caption-lab'>Hardware Lab</div>
                            </div>
                        </div>
                    </a>
                    <a asp-area="" asp-controller="Lab" asp-action="HCRL">
                        <div class='carousel__item carousel__item--desktop-in-3'>
                            <div class='demo-content'>
                                <img src="~/image/LAB/HCRL/2 - HCRL.jpg" alt="HCRL Lab">
                                <div class='caption-lab'>HCRL Lab</div>
                            </div>
                        </div>
                    </a>
                    <a asp-area="" asp-controller="Lab" asp-action="Robot">
                        <div class='carousel__item carousel__item--desktop-in-3'>
                            <div class='demo-content'>
                                <img src="~/image/LAB/ROBOT&IOT/3 - ROBOT&IOT.jpg" alt="Robot & IoT Lab">
                                <div class='caption-lab'>Robot & IoT Lab</div>
                            </div>
                        </div>
                    </a>
                    <a asp-area="" asp-controller="Lab" asp-action="ESL">
                        <div class='carousel__item carousel__item--desktop-in-3'>
                            <div class='demo-content'>
                                <img src="~/image/LAB/ESL/4 - ESL.jpg" alt="ESL Lab">
                                <div class='caption-lab'>ESL Lab</div>
                            </div>
                        </div>
                    </a>
                    <a asp-area="" asp-controller="Lab" asp-action="Network">
                        <div class='carousel__item carousel__item--desktop-in-3'>
                            <div class='demo-content'>
                                <img src="~/image/LAB/NETWORK/5 - NETWORK.jpg" alt="Network Lab">
                                <div class='caption-lab'>Network Lab</div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</body>

</html lang="en">